### ================= IMPORTS =================

In [90]:
import sys
import os
0000
sys.path.append(os.path.abspath("."))
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
import pandas as pd
import numpy as np

In [91]:
df = pd.read_csv(r"D:\Testing_models\KaggleV2-May-2016.csv")

In [92]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [93]:
df.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [94]:
df.value_counts()

PatientId     AppointmentID  Gender  ScheduledDay          AppointmentDay        Age  Neighbourhood      Scholarship  Hipertension  Diabetes  Alcoholism  Handcap  SMS_received  No-show
2.987250e+13  5642903        F       2016-04-29T18:38:08Z  2016-04-29T00:00:00Z  62   JARDIM DA PENHA    0            1             0         0           0        0             No         1
5.589978e+14  5642503        M       2016-04-29T16:08:27Z  2016-04-29T00:00:00Z  56   JARDIM DA PENHA    0            0             0         0           0        0             No         1
4.262962e+12  5642549        F       2016-04-29T16:19:04Z  2016-04-29T00:00:00Z  62   MATA DA PRAIA      0            0             0         0           0        0             No         1
8.679512e+11  5642828        F       2016-04-29T17:29:31Z  2016-04-29T00:00:00Z  8    PONTAL DE CAMBURI  0            0             0         0           0        0             No         1
8.841186e+12  5642494        F       2016-04-29T16:07:23Z  2016-04-29T00:00:00Z  56   JARDIM DA PENHA    0            1             1         0           0        0             No         1
                                                                                                                                                                                           ..
2.572134e+12  5651768        F       2016-05-03T09:15:35Z  2016-06-07T00:00:00Z  56   MARIA ORTIZ        0            0             0         0           0        1             No         1
3.596266e+12  5650093        F       2016-05-03T07:27:33Z  2016-06-07T00:00:00Z  51   MARIA ORTIZ        0            0             0         0           0        1             No         1
1.557663e+13  5630692        F       2016-04-27T16:03:52Z  2016-06-07T00:00:00Z  21   MARIA ORTIZ        0            0             0         0           0        1             No         1
9.213493e+13  5630323        F       2016-04-27T15:09:23Z  2016-06-07T00:00:00Z  38   MARIA ORTIZ        0            0             0         0           0        1             No         1
3.775115e+14  5629448        F       2016-04-27T13:30:56Z  2016-06-07T00:00:00Z  54   MARIA ORTIZ        0            0             0         0           0        1             No         1
Name: count, Length: 110527, dtype: int64

In [95]:
df.describe()

,PatientId,AppointmentID,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [96]:
df['Gender'] = df['Gender'].map({'F' : 0 , 'M' : 1})

In [97]:
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'])

In [98]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,0,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,1,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,0,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,0,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,0,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [99]:
df['Neighbourhood'].unique()

<ArrowStringArray>
[            'JARDIM DA PENHA',               'MATA DA PRAIA',
           'PONTAL DE CAMBURI',                   'REPÚBLICA',
                  'GOIABEIRAS',                  'ANDORINHAS',
                   'CONQUISTA',              'NOVA PALESTINA',
                    'DA PENHA',                  'TABUAZEIRO',
              'BENTO FERREIRA',                   'SÃO PEDRO',
                'SANTA MARTHA',               'SÃO CRISTÓVÃO',
                     'MARUÍPE',              'GRANDE VITÓRIA',
                'SÃO BENEDITO',           'ILHA DAS CAIEIRAS',
                 'SANTO ANDRÉ',                'SOLON BORGES',
                      'BONFIM',              'JARDIM CAMBURI',
                 'MARIA ORTIZ',                      'JABOUR',
             'ANTÔNIO HONÓRIO',                 'RESISTÊNCIA',
         'ILHA DE SANTA MARIA',                 'JUCUTUQUARA',
                  'MONTE BELO',              'MÁRIO CYPRESTE',
               'SANTO ANTÔNIO',                  'BELA VISTA',
                'PRAIA DO SUÁ',                'SANTA HELENA',
                     'ITARARÉ',                  'INHANGUETÁ',
               'UNIVERSITÁRIO',                    'SÃO JOSÉ',
                    'REDENÇÃO',                 'SANTA CLARA',
                      'CENTRO',              'PARQUE MOSCOSO',
                  'DO MOSCOSO',               'SANTOS DUMONT',
                   'CARATOÍRA',         'ARIOVALDO FAVALESSA',
               'ILHA DO FRADE',                    'GURIGICA',
                 'JOANA D´ARC',                  'CONSOLAÇÃO',
              'PRAIA DO CANTO',                   'BOA VISTA',
           'MORADA DE CAMBURI',                 'SANTA LUÍZA',
                 'SANTA LÚCIA',              'BARRO VERMELHO',
                  'ESTRELINHA',              'FORTE SÃO JOÃO',
                'FONTE GRANDE',              'ENSEADA DO SUÁ',
                 'SANTOS REIS',                     'PIEDADE',
           'JESUS DE NAZARETH',                'SANTA TEREZA',
                  'CRUZAMENTO',            'ILHA DO PRÍNCIPE',
                       'ROMÃO',                     'COMDUSA',
               'SANTA CECÍLIA',                  'VILA RUBIM',
                  'DE LOURDES',                   'DO QUADRO',
                   'DO CABRAL',                       'HORTO',
            'SEGURANÇA DO LAR',                 'ILHA DO BOI',
                   'FRADINHOS',                    'NAZARETH',
                   'AEROPORTO', 'ILHAS OCEÂNICAS DE TRINDADE',
           'PARQUE INDUSTRIAL']
Length: 81, dtype: str

In [100]:
freq = df['Neighbourhood'].value_counts()
df['Neighbourhood'] = df['Neighbourhood'].map(freq)

In [101]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,0,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,3877,0,1,0,0,0,0,No
1,5.589978e+14,5642503,1,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,3877,0,0,0,0,0,0,No
2,4.262962e+12,5642549,0,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,644,0,0,0,0,0,0,No
3,8.679512e+11,5642828,0,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,69,0,0,0,0,0,0,No
4,8.841186e+12,5642494,0,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,3877,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,0,2016-05-03 09:15:35+00:00,2016-06-07 00:00:00+00:00,56,5805,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,0,2016-05-03 07:27:33+00:00,2016-06-07 00:00:00+00:00,51,5805,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,0,2016-04-27 16:03:52+00:00,2016-06-07 00:00:00+00:00,21,5805,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,0,2016-04-27 15:09:23+00:00,2016-06-07 00:00:00+00:00,38,5805,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,0,2016-04-27 13:30:56+00:00,2016-06-07 00:00:00+00:00,54,5805,0,0,0,0,0,1,No

In [102]:
df['No-show'] = df['No-show'].map({'No':0,'Yes':1})

In [103]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,0,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,3877,0,1,0,0,0,0,0
1,5.589978e+14,5642503,1,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,3877,0,0,0,0,0,0,0
2,4.262962e+12,5642549,0,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,644,0,0,0,0,0,0,0
3,8.679512e+11,5642828,0,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,69,0,0,0,0,0,0,0
4,8.841186e+12,5642494,0,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,3877,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,0,2016-05-03 09:15:35+00:00,2016-06-07 00:00:00+00:00,56,5805,0,0,0,0,0,1,0
110523,3.596266e+12,5650093,0,2016-05-03 07:27:33+00:00,2016-06-07 00:00:00+00:00,51,5805,0,0,0,0,0,1,0
110524,1.557663e+13,5630692,0,2016-04-27 16:03:52+00:00,2016-06-07 00:00:00+00:00,21,5805,0,0,0,0,0,1,0
110525,9.213493e+13,5630323,0,2016-04-27 15:09:23+00:00,2016-06-07 00:00:00+00:00,38,5805,0,0,0,0,0,1,0
110526,3.775115e+14,5629448,0,2016-04-27 13:30:56+00:00,2016-06-07 00:00:00+00:00,54,5805,0,0,0,0,0,1,0

In [104]:
X = df.drop(['No-show','ScheduledDay','AppointmentDay'], axis=1)
y = df['No-show']

In [105]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [106]:
X_train

,PatientId,AppointmentID,Gender,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
107147,9.376642e+13,5556029,0,42,824,0,0,0,0,0,1
91231,1.998966e+14,5780700,0,16,5805,0,0,0,0,0,0
44278,7.834742e+13,5627148,0,33,2565,0,0,0,0,0,1
21135,3.819235e+14,5738462,1,35,3514,0,1,0,0,0,0
43346,3.642397e+11,5624945,1,43,1071,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
44566,6.555593e+13,5659767,0,28,2018,0,0,0,0,0,0
95816,7.361893e+12,5710032,0,24,452,0,0,0,0,0,1
72173,6.491327e+12,5652649,0,57,1288,0,1,0,1,0,0
100879,4.956329e+11,5743101,0,30,1071,0,1,0,1,0,0
89256,6.139538e+14,5730560,0,32,1977,0,0,0,0,0,1

In [107]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [108]:
# ================= PROBABILISTIC =================
def naive_bayes(X_train, y_train):
    model = GaussianNB()
    model.fit(X_train, y_train)
    return model


def logistic_regression(X_train, y_train):
    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)
    return model


# ================= TREE BASED =================
def decision_tree(X_train, y_train):
    model = DecisionTreeClassifier()
    model.fit(X_train, y_train)
    return model


# ================= ENSEMBLE =================
def random_forest(X_train, y_train):
    model = RandomForestClassifier(n_estimators=100)
    model.fit(X_train, y_train)
    return model


def gradient_boosting(X_train, y_train):
    model = GradientBoostingClassifier()
    model.fit(X_train, y_train)
    return model


def xgboost_model(X_train, y_train):
    model = XGBClassifier(
        n_estimators=100,
        learning_rate=0.1,
        max_depth=5,
        use_label_encoder=False,
        eval_metric='logloss'
    )
    model.fit(X_train, y_train)
    return model

# ================= OTHER MODELS =================
def svm_model(X_train, y_train):
    model = SVC()
    model.fit(X_train, y_train)
    return model

In [109]:
import os
print(os.listdir())

['ml_models.py', 'Models.ipynb', '__pycache__']

In [114]:
from ml_models import get_model
from sklearn.metrics import accuracy_score

# ================= CLASSIFICATION =================
MODEL_LIST = [
    "naive_bayes",
    "logistic_regression",
    "decision_tree",
    "random_forest",
    "gradient_boosting",
    "xgboost"
]

# ================= REGRESSION =================
REGRESSION_MODELS = [
    "linear_regression",
    "ridge",
    "lasso",
    "decision_tree",
    "random_forest",
    "gradient_boosting",
    "svr",
    "xgboost"
]

In [115]:
for model_name in MODEL_LIST:
    
    model = get_model(model_name, X_train, y_train)
    
    # 🔽 STEP 1: prediction
    y_pred = model.predict(X_test)
    
    # 🔽 STEP 2: FIX for XGBoost (ADD HERE)
    if model_name == "xgboost":
        y_pred = (y_pred > 0.5).astype(int)
    
    acc = accuracy_score(y_test, y_pred)
    
    print(f"{model_name} Accuracy: {acc:.4f}")

naive_bayes Accuracy: 0.7773
logistic_regression Accuracy: 0.7952
decision_tree Accuracy: 0.7077
random_forest Accuracy: 0.7910
gradient_boosting Accuracy: 0.7970
xgboost Accuracy: 0.7982

In [112]:
# import sys

# sys.path.append("D:/Testing_models/regression")

# from sklearn.metrics import mean_squared_error, r2_score
# from regression_models import get_regression_model



# for model_name in REGRESSION_MODELS:
#     model = get_regression_model(model_name, X_train, y_train)
    
#     y_pred = model.predict(X_test)
    
#     mse = mean_squared_error(y_test, y_pred)
#     r2 = r2_score(y_test, y_pred)
    
#     print(f"{model_name}")
#     print(f"→ MSE: {mse:.4f}, R2: {r2:.4f}")
#     print()````````````````````````````````````````

In [113]:
# print(type(y_train[0]), y_train[:5])